const dietMap = {
    // Proteins
    "chicken": "fluent-emoji:poultry-leg",
    "chicken breast": "fluent-emoji:poultry-leg",
    "chicken diet": "fluent-emoji:poultry-leg",
    "chicken thigh": "fluent-emoji:poultry-leg",
    "chicken wing": "fluent-emoji:poultry-leg",
    "turkey": "fluent-emoji:turkey",
    "beef": "fluent-emoji:cut-of-meat",
    "steak": "fluent-emoji:cut-of-meat",
    "ground beef": "fluent-emoji:cut-of-meat",
    "meat": "fluent-emoji:cut-of-meat",
    "lamb": "fluent-emoji:cut-of-meat",
    "goat": "fluent-emoji:cut-of-meat",
    "camel": "fluent-emoji:cut-of-meat",
    "fish": "fluent-emoji:fish",
    "salmon": "fluent-emoji:fish",
    "tuna": "fluent-emoji:fish",
    "cod": "fluent-emoji:fish",
    "tilapia": "fluent-emoji:fish",
    "shrimp": "fluent-emoji:shrimp",
    "prawns": "fluent-emoji:shrimp",
    "crab": "fluent-emoji:crab",
    "lobster": "fluent-emoji:lobster",
    "egg": "fluent-emoji:egg",
    "eggs": "fluent-emoji:egg",
    "boiled egg": "fluent-emoji:egg",
    "fried egg": "fluent-emoji:fried-egg",
    "omelette": "fluent-emoji:fried-egg",
    "tofu": "fluent-emoji:bowl-with-spoon",
    "tempeh": "fluent-emoji:bowl-with-spoon",

    // Grains & Carbs
    "rice": "fluent-emoji:cooked-rice",
    "brown rice": "fluent-emoji:cooked-rice",
    "white rice": "fluent-emoji:cooked-rice",
    "basmati rice": "fluent-emoji:cooked-rice",
    "bariis": "fluent-emoji:cooked-rice",
    "pasta": "fluent-emoji:spaghetti",
    "spaghetti": "fluent-emoji:spaghetti",
    "noodles": "fluent-emoji:steaming-bowl",
    "quinoa": "fluent-emoji:bowl-with-spoon",
    "oats": "fluent-emoji:bowl-with-spoon",
    "oatmeal": "fluent-emoji:bowl-with-spoon",
    "porridge": "fluent-emoji:bowl-with-spoon",
    "bread": "fluent-emoji:bread",
    "white bread": "fluent-emoji:bread",
    "brown bread": "fluent-emoji:bread",
    "whole wheat bread": "fluent-emoji:bread",
    "baguette": "fluent-emoji:baguette-bread",
    "croissant": "fluent-emoji:croissant",
    "toast": "fluent-emoji:bread",
    "muufo": "fluent-emoji:flatbread",
    "sabayad": "fluent-emoji:flatbread",
    "canjeero": "fluent-emoji:pancakes",
    "laxox": "fluent-emoji:pancakes",
    "potato": "fluent-emoji:potato",
    "baked potato": "fluent-emoji:potato",
    "sweet potato": "fluent-emoji:roasted-sweet-potato",
    "fries": "fluent-emoji:french-fries",
    "cereal": "fluent-emoji:bowl-with-spoon",

    // Fruits
    "apple": "fluent-emoji:red-apple",
    "apples": "fluent-emoji:red-apple",
    "green apple": "fluent-emoji:green-apple",
    "banana": "fluent-emoji:banana",
    "bananas": "fluent-emoji:banana",
    "orange": "fluent-emoji:tangerine",
    "tangerine": "fluent-emoji:tangerine",
    "grapes": "fluent-emoji:grapes",
    "strawberry": "fluent-emoji:strawberry",
    "strawberries": "fluent-emoji:strawberry",
    "blueberry": "fluent-emoji:blueberries",
    "blueberries": "fluent-emoji:blueberries",
    "raspberry": "fluent-emoji:strawberry",
    "cherry": "fluent-emoji:cherries",
    "mango": "fluent-emoji:mango",
    "pineapple": "fluent-emoji:pineapple",
    "watermelon": "fluent-emoji:watermelon",
    "melon": "fluent-emoji:melon",
    "kiwi": "fluent-emoji:kiwi-fruit",
    "pear": "fluent-emoji:pear",
    "peach": "fluent-emoji:peach",
    "lemon": "fluent-emoji:lemon",
    "lime": "fluent-emoji:lemon",
    "avocado": "fluent-emoji:avocado",
    "pomegranate": "fluent-emoji:pomegranate",
    "coconut": "fluent-emoji:coconut",
    "papaya": "fluent-emoji:mango",
    "moos": "fluent-emoji:banana",
    "tufaax": "fluent-emoji:red-apple",
    "liin": "fluent-emoji:tangerine",
    "canab": "fluent-emoji:grapes",
    "cambe": "fluent-emoji:mango",

    // Vegetables
    "salad": "fluent-emoji:green-salad",
    "lettuce": "fluent-emoji:leafy-green",
    "spinach": "fluent-emoji:leafy-green",
    "broccoli": "fluent-emoji:broccoli",
    "carrot": "fluent-emoji:carrot",
    "carrots": "fluent-emoji:carrot",
    "cucumber": "fluent-emoji:cucumber",
    "tomato": "fluent-emoji:tomato",
    "tomatoes": "fluent-emoji:tomato",
    "onion": "fluent-emoji:onion",
    "garlic": "fluent-emoji:garlic",
    "pepper": "fluent-emoji:bell-pepper",
    "bell pepper": "fluent-emoji:bell-pepper",
    "chili": "fluent-emoji:hot-pepper",
    "corn": "fluent-emoji:ear-of-corn",
    "eggplant": "fluent-emoji:eggplant",
    "mushroom": "fluent-emoji:mushroom",
    "peas": "fluent-emoji:leafy-green",
    "beans": "fluent-emoji:beans",
    "cabbage": "fluent-emoji:leafy-green",
    "shigni": "fluent-emoji:hot-pepper",

    // Dairy & Healthy Fats
    "milk": "fluent-emoji:glass-of-milk",
    "yogurt": "fluent-emoji:bowl-with-spoon",
    "cheese": "fluent-emoji:cheese-wedge",
    "butter": "fluent-emoji:butter",
    "olive oil": "fluent-emoji:drop-of-blood",
    "honey": "fluent-emoji:honey-pot",
    "nuts": "fluent-emoji:peanuts",
    "peanut": "fluent-emoji:peanuts",
    "almonds": "fluent-emoji:peanuts",
    "walnuts": "fluent-emoji:peanuts",
    "peanut butter": "fluent-emoji:peanuts",

    // Beverages
    "water": "fluent-emoji:droplet",
    "juice": "fluent-emoji:cup-with-straw",
    "orange juice": "fluent-emoji:cup-with-straw",
    "apple juice": "fluent-emoji:cup-with-straw",
    "coffee": "fluent-emoji:hot-beverage",
    "tea": "fluent-emoji:teacup-without-handle",
    "green tea": "fluent-emoji:teacup-without-handle",
    "smoothie": "fluent-emoji:cup-with-straw",
    "soda": "fluent-emoji:beverage-box",
    "shaah": "fluent-emoji:teacup-without-handle",
    "biyo": "fluent-emoji:droplet",

    // Snacks & Others
    "pizza": "fluent-emoji:pizza",
    "burger": "fluent-emoji:hamburger",
    "sandwich": "fluent-emoji:sandwich",
    "taco": "fluent-emoji:taco",
    "burrito": "fluent-emoji:burrito",
    "sushi": "fluent-emoji:sushi",
    "soup": "fluent-emoji:pot-of-food",
    "maraq": "fluent-emoji:pot-of-food",
    "cookie": "fluent-emoji:cookie",
    "cake": "fluent-emoji:shortcake",
    "chocolate": "fluent-emoji:chocolate-bar",
    "ice cream": "fluent-emoji:soft-ice-cream",
    "popcorn": "fluent-emoji:popcorn",
    "malamuud": "fluent-emoji:shortcake",
    "xalwo": "fluent-emoji:custard",
    "oodkac": "fluent-emoji:cut-of-meat",
    "muufo baadiye": "fluent-emoji:flatbread",
    "suqaar": "fluent-emoji:stew",
    "kaluun": "fluent-emoji:fish",
    "baasto": "fluent-emoji:spaghetti",
    "odkac": "fluent-emoji:cut-of-meat",

    // More Proteins
    "venison": "fluent-emoji:cut-of-meat",
    "bacon": "fluent-emoji:bacon",
    "ham": "fluent-emoji:meat-on-bone",
    "salami": "fluent-emoji:meat-on-bone",
    "sausage": "fluent-emoji:hot-dog",
    "hot dog": "fluent-emoji:hot-dog",
    "meatballs": "fluent-emoji:stew",
    "lamb chops": "fluent-emoji:cut-of-meat",
    "scallops": "fluent-emoji:shell",
    "mussels": "fluent-emoji:shell",
    "oysters": "fluent-emoji:shell",
    "calamari": "fluent-emoji:squid",
    "octopus": "fluent-emoji:octopus",

    // More Fruits
    "grapefruit": "fluent-emoji:tangerine",
    "plum": "fluent-emoji:grapes",
    "apricot": "fluent-emoji:peach",
    "nectarine": "fluent-emoji:peach",
    "fig": "fluent-emoji:grapes",
    "date": "fluent-emoji:grapes",
    "dates": "fluent-emoji:grapes",
    "tamarind": "fluent-emoji:beans",
    "guava": "fluent-emoji:pear",
    "lychee": "fluent-emoji:strawberry",
    "dragon fruit": "fluent-emoji:pitaya",
    "star fruit": "fluent-emoji:star",
    "passion fruit": "fluent-emoji:grapes",
    "cranberry": "fluent-emoji:cherries",
    "blackberry": "fluent-emoji:blueberries",

    // More Vegetables
    "asparagus": "fluent-emoji:leafy-green",
    "zucchini": "fluent-emoji:cucumber",
    "cauliflower": "fluent-emoji:broccoli",
    "spinach": "fluent-emoji:leafy-green",
    "kale": "fluent-emoji:leafy-green",
    "sweet corn": "fluent-emoji:ear-of-corn",
    "radish": "fluent-emoji:carrot",
    "pumpkin": "fluent-emoji:pumpkin",
    "squash": "fluent-emoji:pumpkin",
    "leek": "fluent-emoji:garlic",
    "celery": "fluent-emoji:broccoli",
    "brussels sprouts": "fluent-emoji:broccoli",
    "artichoke": "fluent-emoji:broccoli",
    "okra": "fluent-emoji:cucumber",
    "yam": "fluent-emoji:roasted-sweet-potato",

    // More Grains & Breakfast
    "pancakes": "fluent-emoji:pancakes",
    "waffles": "fluent-emoji:waffle",
    "bagel": "fluent-emoji:bagel",
    "donut": "fluent-emoji:doughnut",
    "muffin": "fluent-emoji:cupcake",
    "pastry": "fluent-emoji:pie",
    "granola": "fluent-emoji:bowl-with-spoon",
    "muesli": "fluent-emoji:bowl-with-spoon",
    "couscous": "fluent-emoji:cooked-rice",
    "bulgur": "fluent-emoji:cooked-rice",

    // More Snacks & Junk
    "chips": "fluent-emoji:potato-chips",
    "pretzels": "fluent-emoji:pretzel",
    "popcorn": "fluent-emoji:popcorn",
    "candy": "fluent-emoji:candy",
    "lollipop": "fluent-emoji:lollipop",
    "jam": "fluent-emoji:strawberry",
    "syrup": "fluent-emoji:pancakes",
    "ketchup": "fluent-emoji:tomato",
    "mayonnaise": "fluent-emoji:egg",
    "mustard": "fluent-emoji:lemon",

    // Drinks Expansion
    "milkshake": "fluent-emoji:cup-with-straw",
    "iced coffee": "fluent-emoji:beverage-box",
    "latte": "fluent-emoji:hot-beverage",
    "cappuccino": "fluent-emoji:hot-beverage",
    "espresso": "fluent-emoji:hot-beverage",
    "hot chocolate": "fluent-emoji:hot-beverage",
    "red bull": "fluent-emoji:beverage-box",
    "energy drink": "fluent-emoji:beverage-box",
    "wine": "fluent-emoji:wine-glass",
    "beer": "fluent-emoji:beer-mug",
    "whiskey": "fluent-emoji:tumbler-glass",
    "cocktail": "fluent-emoji:cocktail-glass",

    // Somali Specific
    "canjeero xabashi": "fluent-emoji:pancakes",
    "malawah": "fluent-emoji:pancakes",
    "sabayad": "fluent-emoji:flatbread",
    "bur": "fluent-emoji:bread",
    "qamadi": "fluent-emoji:ear-of-rice",
    "misir": "fluent-emoji:beans",
    "digir": "fluent-emoji:beans",
    "cambuulo": "fluent-emoji:stew",
    "baasto hilib leh": "fluent-emoji:spaghetti",
    "bariis pilaf": "fluent-emoji:cooked-rice",
    "liin dhanaaan": "fluent-emoji:lemon",
    "liin macaan": "fluent-emoji:tangerine",
    "caano geel": "fluent-emoji:glass-of-milk",
    "caano lo'aad": "fluent-emoji:glass-of-milk",
    "maraq hilib": "fluent-emoji:pot-of-food",
    "sambusa": "fluent-emoji:fortune-cookie",
    "bajiyo": "fluent-emoji:falafel",
    "kabaab": "fluent-emoji:meat-on-bone",
    "hilib ari": "fluent-emoji:cut-of-meat",
    "hilib loaad": "fluent-emoji:cut-of-meat",
    "hilib geel": "fluent-emoji:cut-of-meat",
};

const workoutMap = {
    // Chest (Pectorals)
    "bench press": "healthicons:exercise-bench-press",
    "barbell bench press": "healthicons:exercise-bench-press",
    "dumbbell bench press": "healthicons:exercise-bench-press",
    "incline bench press": "healthicons:exercise-bench-press",
    "decline bench press": "healthicons:exercise-bench-press",
    "chest press": "healthicons:exercise-bench-press",
    "machine chest press": "healthicons:exercise-bench-press",
    "dumbbell fly": "healthicons:exercise-bench-press",
    "cable fly": "healthicons:exercise-bench-press",
    "pec deck": "healthicons:exercise-bench-press",
    "pushup": "healthicons:exercise-pushups",
    "weighted pushup": "healthicons:exercise-pushups",
    "dips": "healthicons:exercise-pullups",
    "chest dips": "healthicons:exercise-pullups",

    // Back (Lats, Traps, Rhomboids)
    "deadlift": "healthicons:exercise-deadlift",
    "barbell deadlift": "healthicons:exercise-deadlift",
    "sumo deadlift": "healthicons:exercise-deadlift",
    "romanian deadlift": "healthicons:exercise-deadlift",
    "rdl": "healthicons:exercise-deadlift",
    "pullup": "healthicons:exercise-pullups",
    "chinup": "healthicons:exercise-pullups",
    "lat pulldown": "healthicons:exercise-pullups",
    "seated row": "healthicons:exercise-rowing",
    "barbell row": "healthicons:exercise-rowing",
    "dumbbell row": "healthicons:exercise-rowing",
    "t-bar row": "healthicons:exercise-rowing",
    "face pulls": "healthicons:exercise-weights",
    "shrugs": "healthicons:exercise-weights",
    "back extension": "healthicons:exercise-weights",

    // Shoulders (Deltoids)
    "military press": "healthicons:exercise-weights",
    "overhead press": "healthicons:exercise-weights",
    "shoulder press": "healthicons:exercise-weights",
    "arnold press": "healthicons:exercise-weights",
    "lateral raise": "healthicons:exercise-weights",
    "front raise": "healthicons:exercise-weights",
    "rear delt fly": "healthicons:exercise-weights",
    "upright row": "healthicons:exercise-weights",

    // Legs (Quads, Hamstrings, Glutes, Calves)
    "squat": "healthicons:exercise-squats",
    "barbell squat": "healthicons:exercise-squats",
    "goblet squat": "healthicons:exercise-squats",
    "leg press": "healthicons:exercise-squats",
    "leg extension": "healthicons:exercise-squats",
    "leg curl": "healthicons:exercise-squats",
    "lunge": "healthicons:exercise-squats",
    "walking lunge": "healthicons:exercise-squats",
    "bulgarian split squat": "healthicons:exercise-squats",
    "step ups": "healthicons:exercise-squats",
    "calf raise": "healthicons:exercise-squats",
    "standing calf raise": "healthicons:exercise-squats",
    "seated calf raise": "healthicons:exercise-squats",
    "hip thrust": "healthicons:exercise-squats",
    "glute bridge": "healthicons:exercise-squats",

    // Arms (Biceps, Triceps, Forearms)
    "bicep curl": "healthicons:exercise-weights",
    "barbell curl": "healthicons:exercise-weights",
    "dumbbell curl": "healthicons:exercise-weights",
    "hammer curl": "healthicons:exercise-weights",
    "preacher curl": "healthicons:exercise-weights",
    "concentration curl": "healthicons:exercise-weights",
    "tricep pushdown": "healthicons:exercise-weights",
    "skull crusher": "healthicons:exercise-weights",
    "tricep extension": "healthicons:exercise-weights",
    "overhead tricep extension": "healthicons:exercise-weights",
    "tricep kickback": "healthicons:exercise-weights",
    "wrist curl": "healthicons:exercise-weights",

    // Core (Abs, Obliques)
    "crunch": "healthicons:exercise-yoga",
    "situp": "healthicons:exercise-yoga",
    "plank": "healthicons:exercise-yoga",
    "russian twist": "healthicons:exercise-yoga",
    "leg raise": "healthicons:exercise-yoga",
    "hanging leg raise": "healthicons:exercise-yoga",
    "ab wheel": "healthicons:exercise-yoga",
    "bicycle crunch": "healthicons:exercise-yoga",
    "mountain climber": "healthicons:exercise-running",

    // Cardio & Mobility
    "run": "healthicons:exercise-running",
    "running": "healthicons:exercise-running",
    "treadmill": "healthicons:exercise-running",
    "walk": "healthicons:exercise-walk",
    "walking": "healthicons:exercise-walk",
    "cycling": "healthicons:exercise-bicycle",
    "bike": "healthicons:exercise-bicycle",
    "swim": "healthicons:exercise-swimming",
    "swimming": "healthicons:exercise-swimming",
    "jump rope": "healthicons:exercise-weights",
    "box jump": "healthicons:exercise-squats",
    "burpee": "healthicons:exercise-pushups",
    "yoga": "healthicons:exercise-yoga",
    "stretching": "healthicons:exercise-yoga",

    // Somali
    "jimicsi": "healthicons:exercise-weights",
    "almiito": "healthicons:exercise-weights",
    "oris": "healthicons:exercise-running",
    "socod": "healthicons:exercise-walk",
    "dabaasha": "healthicons:exercise-swimming",
    "baaskiil": "healthicons:exercise-bicycle",
    "dhidid": "healthicons:exercise-weights",

    // Categories (Used in Phase rendering)
    "upper body": "healthicons:exercise-weights",
    "core": "healthicons:exercise-yoga",
    "lower body": "healthicons:exercise-squats",
    "warm up": "fluent-emoji:fire",
    "cardio": "healthicons:exercise-running",
    "cool down": "fluent-emoji:snowflake"
};

function getEmojiForText(text, context = 'diet') {
    if (!text || typeof text !== 'string') return "<span style='color:#cbd5e1'>🔹</span>";
    let lowerText = text.toLowerCase().trim();

    const activeMap = context === 'diet' ? dietMap : workoutMap;

    // Direct match first
    if (activeMap[lowerText]) {
        return `<iconify-icon icon="${activeMap[lowerText]}" width="32" height="32" style="vertical-align:middle; display:inline-block;"></iconify-icon>`;
    }

    // Sort keys by length descending to match longest phrases first
    const sortedKeys = Object.keys(activeMap).sort((a, b) => b.length - a.length);

    for (const key of sortedKeys) {
        if (lowerText.includes(key)) {
            return `<iconify-icon icon="${activeMap[key]}" width="32" height="32" style="vertical-align:middle; display:inline-block;"></iconify-icon>`;
        }
    }

    // Default fallback (Simple colored diamond)
    return "<span style='color:#3b82f6; font-size:24px;'>✦</span>";
}
