<?php
session_start();
include_once "dbcon.php";
include_once "session.php";

if (!isset($_SESSION['user_id'])) {
  header('location:../index.php');
  exit();
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <title>M * A GYM System</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="../css/bootstrap.min.css" />
  <link rel="stylesheet" href="../css/bootstrap-responsive.min.css" />
  <link rel="stylesheet" href="../css/fullcalendar.css" />
  <link rel="stylesheet" href="../css/matrix-style.css" />
  <link rel="stylesheet" href="../css/matrix-media.css" />
  <link href="../font-awesome/css/all.css" rel="stylesheet" />
  <link rel="stylesheet" href="../css/jquery.gritter.css" />
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>

<body>

  <!--Header-part-->
  <!-- Logo removed per user request -->
  <!--close-Header-part-->


  <!--top-Header-menu-->
  <?php include '../includes/topheader.php' ?>
  <!--close-top-Header-menu-->

  <!--start-top-serch-->
  <!-- <div id="search">
  <input type="hidden" placeholder="Search here..."/>
  <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
</div> -->
  <!--close-top-serch-->
  <!--sidebar-menu-->
  <?php $page = "reminder";
  include '../includes/sidebar.php' ?>
  <!--sidebar-menu-->

  <!--main-container-part-->
  <div id="content">
    <!--breadcrumbs-->
    <div id="content-header">
      <div id="breadcrumb"> <a href="index.php" title="You're right here" class="tip-bottom"><i class="fas fa-home"></i> Home</a></div>
    </div>
    <!--End-breadcrumbs-->

    <!--Action boxes-->
    <div class="container-fluid" style="margin-top: 80px;">

      <!--End-Action boxes-->

      <div class="row-fluid">




        <div class="span12">

          <?php
          $qry = "SELECT reminder FROM members WHERE user_id='" . $_SESSION['user_id'] . "'";
          $cnt = 1;
          $result = mysqli_query($con, $qry);




          while ($row = mysqli_fetch_array($result)) { ?>


            <?php if ($row['reminder'] == '1') { ?>

              <div class="alert alert-danger" role="alert" style="border-left: 5px solid #dc3545; background-color: #fff5f5; color: #721c24; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(220, 53, 69, 0.1);">
                <h4 class="alert-heading" style="color: #c82333; font-weight: 800; font-size: 24px; margin-bottom: 15px; display: flex; align-items: center; gap: 10px;">
                  <i class="fas fa-exclamation-triangle"></i> DIGNIIN MUHIIM AH (ALERT)
                </h4>
                <p style="font-size: 16px; line-height: 1.8; color: #444;">Halkan waxaan kuugu ogeysiinaynaa in barnaamijkaaga xubinnimo ee hadda uu <strong>dhawaan dhacayo</strong>. Fadlan iska bixi lacagaha lagugu leeyahay ka hor intaanay gaadhin taariikhda laguu qabtay.</p>
                <div style="background: #fff; padding: 15px; border-radius: 8px; border: 1px dashed #dc3545; margin: 20px 0;">
                  <p style="margin: 0; font-weight: 700; color: #c82333;"><i class="fas fa-info-circle"></i> WAA MUHIIM INAAD LACAGTA WAQTIGEEDA ISKA BIXISO SI LOOGA TAXADARO INUU ADEEGGU KAA JOOGSADO.</p>
                </div>
                <hr style="border-top: 1px solid #f5c6cb; margin: 25px 0;">
                <div style="display: flex; justify-content: space-between; align-items: flex-end; flex-wrap: wrap; gap: 20px;">
                  <div style="flex: 1; min-width: 250px;">
                    <p class="mb-0" style="font-style: italic; color: #666;">Waxaan kugu qaddarinaynaa inaad tahay macmiilkeena, waxaana rajaynaynaa inaan sii wadno adeegga aan kuu hayno mustaqbalka.</p>
                  </div>

                  <div class="pull-right" style="text-align: center;">
                    <h4 style="margin: 0; color: #1e293b; font-size: 16px;">Approved By:</h4>
                    <img src="../../img/report/stamp-sample.png" style="width: 124px; margin: 10px 0;" alt="Stamp">
                    <p class="text-center" style="font-size: 12px; color: #94a3b8; margin: 0;">Note: AutoGenerated</p>
                  </div>
                </div>
              </div>

            <?php } else { ?>

              <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">NO REMINDERS YET!</h4>
              </div>

          <?php }
          } ?>


        </div>


      </div><!-- End of row-fluid -->
    </div><!-- End of container-fluid -->
  </div><!-- End of content-ID -->

  <!--end-main-container-part-->

  <!--Footer-part-->

  <div class="row-fluid">
    <div id="footer" class="span12"> <?php echo date("Y"); ?> &copy; M * A GYM System Developed By Abdikafi</a> </div>
  </div>

  <style>
    #footer {
      color: white;
    }
  </style>

  <!--end-Footer-part-->

  <script src="../js/excanvas.min.js"></script>
  <script src="../js/jquery.min.js"></script>
  <script src="../js/jquery.ui.custom.js"></script>
  <script src="../js/bootstrap.min.js"></script>
  <script src="../js/jquery.flot.min.js"></script>
  <script src="../js/jquery.flot.resize.min.js"></script>
  <script src="../js/jquery.peity.min.js"></script>
  <script src="../js/fullcalendar.min.js"></script>
  <script src="../js/matrix.js"></script>
  <script src="../js/matrix.dashboard.js"></script>
  <script src="../js/jquery.gritter.min.js"></script>
  <script src="../js/matrix.interface.js"></script>
  <script src="../js/matrix.chat.js"></script>
  <script src="../js/jquery.validate.js"></script>
  <script src="../js/matrix.form_validation.js"></script>
  <script src="../js/jquery.wizard.js"></script>
  <script src="../js/jquery.uniform.js"></script>
  <script src="../js/select2.min.js"></script>
  <script src="../js/matrix.popover.js"></script>
  <script src="../js/jquery.dataTables.min.js"></script>
  <script src="../js/matrix.tables.js"></script>

  <script type="text/javascript">
    // This function is called from the pop-up menus to transfer to
    // a different page. Ignore if the value returned is a null string:
    function goPage(newURL) {

      // if url is empty, skip the menu dividers and reset the menu selection to default
      if (newURL != "") {

        // if url is "-", it is this page -- reset the menu:
        if (newURL == "-") {
          resetMenu();
        }
        // else, send page to designated URL            
        else {
          document.location.href = newURL;
        }
      }
    }

    // resets the menu selection upon entry to this page:
    function resetMenu() {
      document.gomenu.selector.selectedIndex = 2;
    }
  </script>
</body>

</html>